name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
    
      - name: Setup Node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
      - run: npm install
      - run: npm run build:test